# Generated by Django 3.0.2 on 2020-02-20 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutMe',
            new_name='Bio',
        ),
    ]
