# Generated by Django 3.0.2 on 2020-02-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200220_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=models.ImageField(default='pictures/profile/default.jpg', upload_to='pictures/profile'),
        ),
    ]
