# Generated by Django 3.0.2 on 2020-02-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20200221_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=models.ImageField(default='static/img/profile/default.jpg', upload_to='static/profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='static/img/project/default_project.jpg', upload_to='static/project'),
        ),
    ]
