# Generated by Django 3.0.2 on 2020-02-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20200221_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=models.FilePathField(path='/static/img/profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/static/img/project'),
        ),
    ]
