# Generated by Django 3.0.2 on 2020-02-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20200221_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gitRepo',
            field=models.TextField(default='webpage.com'),
        ),
    ]
