# Generated by Django 3.0.2 on 2020-02-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_project_gitrepo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.TextField(default='Summer 1969'),
        ),
    ]
