# Generated by Django 3.0.2 on 2020-11-02 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hidden_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
